//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IFFCIConnect
{
    using System;
    using System.Collections.Generic;
    
    public partial class Industry_Master
    {
        public int id { get; set; }
        public string Name { get; set; }
        public bool IsActive { get; set; }
    }
}
