//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IFFCIConnect
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Seeker_ExperinceDetails
    {
        public int id { get; set; }
        public int Seeker_id { get; set; }
        public Nullable<bool> Is_Current_Job { get; set; }
        public Nullable<System.DateTime> Start_Date { get; set; }
        public Nullable<System.DateTime> End_Date { get; set; }
        public string Job_Title { get; set; }
        public string Company_Name { get; set; }
        public string Job_Location_City { get; set; }
        public string Job_Location_State { get; set; }
        public string Job_Location_Country { get; set; }
        public string Description { get; set; }
        public System.DateTime CreatedDate { get; set; }
    }
}
