//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IFFCIConnect
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Employer_JobPost
    {
        public int id { get; set; }
        public int Employer_id { get; set; }
        public string Experince { get; set; }
        public string Skills_set { get; set; }
        public string NoOfOpening { get; set; }
        public string JobTitle { get; set; }
        public Nullable<System.DateTime> JobPostDateTime { get; set; }
        public string JobFile { get; set; }
        public string Status { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual Tbl_Employer_Account Tbl_Employer_Account { get; set; }
    }
}
