//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IFFCIConnect
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Seeker_EducationDetails
    {
        public int id { get; set; }
        public int Seeker_id { get; set; }
        public string Certificate_Degree_Name { get; set; }
        public string Major_Subjects { get; set; }
        public string Institute_University_Name { get; set; }
        public Nullable<System.DateTime> Starting_Date { get; set; }
        public Nullable<System.DateTime> Completion_Date { get; set; }
        public string Percentage { get; set; }
        public string CGPA { get; set; }
        public bool Is_active { get; set; }
        public System.DateTime CreatedDate { get; set; }
    
        public virtual Tbl_Seeker_Account Tbl_Seeker_Account { get; set; }
    }
}
