//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IFFCIConnect
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Employer_Account
    {
        public int id { get; set; }
        public int user_type_id { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string Company_Name { get; set; }
        public string Industry { get; set; }
        public string Org_Type { get; set; }
        public string Landline_Phone { get; set; }
        public string Contact_Number { get; set; }
        public string Company_Address { get; set; }
        public string Company_website_URL { get; set; }
        public string Company_Video { get; set; }
        public string Number_of_Employees { get; set; }
        public string Company_Description { get; set; }
        public bool Is_active { get; set; }
        public string Full_Name { get; set; }
        public Nullable<bool> Email_notification_active { get; set; }
        public System.DateTime registration_date { get; set; }
        public Nullable<bool> SMS_notification_active { get; set; }
        public string GST_Number { get; set; }
        public string Designation { get; set; }
        public string Company_logo { get; set; }
    }
}
