//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IFFCIConnect
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_SkillsMyAppointments
    {
        public int id { get; set; }
        public int Seeker_id { get; set; }
        public string EmployerName { get; set; }
        public string JobTitle { get; set; }
        public Nullable<System.DateTime> DateTime { get; set; }
        public string Status { get; set; }
        public Nullable<bool> Action { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public System.DateTime CreatedDate { get; set; }
    }
}
